// src/pages/Users.tsx
import { useState, useEffect } from "react";
import { Plus, Pencil, KeyRound, Trash2, Loader2 } from "lucide-react";
import { format } from "date-fns";
import { ptBR } from "date-fns/locale";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

import { User } from "@/types/user";
import { usersService } from "@/services/users";
import DashboardLayout from "@/components/DashboardLayout";

type ModalType = "create" | "edit" | "password" | null;

const Users = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [modalType, setModalType] = useState<ModalType>(null);
  const [selectedUser, setSelectedUser] = useState<User | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Form states
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [role, setRole] = useState<"admin" | "member">("member");

  useEffect(() => {
    loadUsers();
  }, []);

  const loadUsers = async () => {
    setIsLoading(true);
    try {
      const data = await usersService.getAll();
      setUsers(data);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro ao carregar usuários";
      toast.error(message);
    } finally {
      setIsLoading(false);
    }
  };

  const resetForm = () => {
    setEmail("");
    setPassword("");
    setRole("member");
    setSelectedUser(null);
  };

  const openCreateModal = () => {
    resetForm();
    setModalType("create");
  };

  const openEditModal = (user: User) => {
    setSelectedUser(user);
    setEmail(user.email);
    setRole(user.role);
    setModalType("edit");
  };

  const openPasswordModal = (user: User) => {
    setSelectedUser(user);
    setPassword("");
    setModalType("password");
  };

  const closeModal = () => {
    setModalType(null);
    resetForm();
  };

  const handleCreate = async () => {
    if (!email || !password || password.length < 6) {
      toast.error("Preencha todos os campos corretamente. A senha deve ter no mínimo 6 caracteres.");
      return;
    }

    setIsSubmitting(true);
    try {
      const newUser = await usersService.create({ email, password, role });
      setUsers([...users, newUser]);
      toast.success("Usuário criado com sucesso!");
      closeModal();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro ao criar usuário";
      toast.error(message);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleEdit = async () => {
    if (!email || !selectedUser) {
      toast.error("Preencha todos os campos corretamente.");
      return;
    }

    setIsSubmitting(true);
    try {
      const updatedUser = await usersService.update(selectedUser.id, { email, role });
      setUsers(users.map((u) => (u.id === selectedUser.id ? updatedUser : u)));
      toast.success("Usuário atualizado com sucesso!");
      closeModal();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro ao atualizar usuário";
      toast.error(message);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handlePasswordChange = async () => {
    if (!password || password.length < 6 || !selectedUser) {
      toast.error("A senha deve ter no mínimo 6 caracteres.");
      return;
    }

    setIsSubmitting(true);
    try {
      await usersService.changePassword(selectedUser.id, { password });
      toast.success("Senha alterada com sucesso!");
      closeModal();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro ao alterar senha";
      toast.error(message);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDelete = async (user: User) => {
    if (!confirm(`Tem certeza que deseja excluir o usuário ${user.email}?`)) {
      return;
    }

    try {
      await usersService.delete(user.id);
      setUsers(users.filter((u) => u.id !== user.id));
      toast.success("Usuário excluído com sucesso!");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro ao excluir usuário";
      toast.error(message);
    }
  };

  const getInitials = (name: string) => {
    return name
      .split(" ")
      .map((n) => n[0])
      .join("")
      .toUpperCase()
      .slice(0, 2);
  };

  return (
    <DashboardLayout>
      <div className="p-6 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-foreground">
            Gestão de Usuários
          </h1>
            <Button onClick={openCreateModal}>
              <Plus className="h-4 w-4 mr-2" />
              Novo Usuário
            </Button>
          </div>

          {/* Table Card */}
          <Card>
            <CardHeader>
              <CardTitle>Usuários</CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-12">ID</TableHead>
                    <TableHead>Membro</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>Função</TableHead>
                    <TableHead>Criado em</TableHead>
                    <TableHead className="text-right">Ações</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {isLoading ? (
                    <TableRow>
                      <TableCell colSpan={6} className="text-center py-8">
                        <div className="flex items-center justify-center gap-2">
                          <Loader2 className="h-5 w-5 animate-spin" />
                          <span>Carregando...</span>
                        </div>
                      </TableCell>
                    </TableRow>
                  ) : users.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={6} className="text-center py-8 text-muted-foreground">
                        Nenhum usuário encontrado
                      </TableCell>
                    </TableRow>
                  ) : (
                    users.map((user) => (
                      <TableRow key={user.id}>
                        <TableCell className="font-mono text-muted-foreground">
                          {user.id}
                        </TableCell>
                        <TableCell>
                          {user.member ? (
                            <div className="flex items-center gap-3">
                              <Avatar className="h-8 w-8">
                                <AvatarImage src={user.member.photoUrl} />
                                <AvatarFallback>
                                  {getInitials(user.member.name)}
                                </AvatarFallback>
                              </Avatar>
                              <span className="font-medium">{user.member.name}</span>
                            </div>
                          ) : (
                            <span className="text-muted-foreground">—</span>
                          )}
                        </TableCell>
                        <TableCell>{user.email}</TableCell>
                        <TableCell>
                          <Badge
                            variant={user.role === "admin" ? "default" : "secondary"}
                          >
                            {user.role === "admin" ? "Administrador" : "Membro"}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          {format(new Date(user.createdAt), "dd/MM/yyyy", { locale: ptBR })}
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="flex items-center justify-end gap-2">
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => openEditModal(user)}
                              title="Editar"
                            >
                              <Pencil className="h-4 w-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => openPasswordModal(user)}
                              title="Alterar senha"
                            >
                              <KeyRound className="h-4 w-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => handleDelete(user)}
                              title="Excluir"
                              className="text-destructive hover:text-destructive"
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>

        {/* Create User Modal */}
        <Dialog open={modalType === "create"} onOpenChange={() => closeModal()}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Criar Usuário</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <Label htmlFor="email">Email *</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="usuario@email.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  disabled={isSubmitting}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Senha *</Label>
                <Input
                  id="password"
                  type="password"
                  placeholder="Mínimo 6 caracteres"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  disabled={isSubmitting}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="role">Função *</Label>
                <Select value={role} onValueChange={(v: "admin" | "member") => setRole(v)} disabled={isSubmitting}>
                  <SelectTrigger>
                    <SelectValue placeholder="Selecione uma função" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="member">Membro</SelectItem>
                    <SelectItem value="admin">Administrador</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={closeModal} disabled={isSubmitting}>
                Cancelar
              </Button>
              <Button onClick={handleCreate} disabled={isSubmitting}>
                {isSubmitting ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Criando...
                  </>
                ) : (
                  "Criar"
                )}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Edit User Modal */}
        <Dialog open={modalType === "edit"} onOpenChange={() => closeModal()}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Editar Usuário</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <Label htmlFor="edit-email">Email *</Label>
                <Input
                  id="edit-email"
                  type="email"
                  placeholder="usuario@email.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  disabled={isSubmitting}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit-role">Função *</Label>
                <Select value={role} onValueChange={(v: "admin" | "member") => setRole(v)} disabled={isSubmitting}>
                  <SelectTrigger>
                    <SelectValue placeholder="Selecione uma função" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="member">Membro</SelectItem>
                    <SelectItem value="admin">Administrador</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={closeModal} disabled={isSubmitting}>
                Cancelar
              </Button>
              <Button onClick={handleEdit} disabled={isSubmitting}>
                {isSubmitting ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Salvando...
                  </>
                ) : (
                  "Salvar"
                )}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Change Password Modal */}
        <Dialog open={modalType === "password"} onOpenChange={() => closeModal()}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Alterar Senha</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <p className="text-sm text-muted-foreground">
                Alterando senha do usuário: <strong>{selectedUser?.email}</strong>
              </p>
              <div className="space-y-2">
                <Label htmlFor="new-password">Nova Senha *</Label>
                <Input
                  id="new-password"
                  type="password"
                  placeholder="Mínimo 6 caracteres"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  disabled={isSubmitting}
                />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={closeModal} disabled={isSubmitting}>
                Cancelar
              </Button>
              <Button onClick={handlePasswordChange} disabled={isSubmitting}>
                {isSubmitting ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Alterando...
                  </>
                ) : (
                  "Alterar Senha"
                )}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </DashboardLayout>
  );
};

export default Users;

// src/app/pages/users/users.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { UsersService, User, CreateUserRequest, UpdateUserRequest } from '../../services/users.service';

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './users.component.html',
  styleUrl: './users.component.scss'
})
export class UsersComponent implements OnInit {
  users: User[] = [];
  filteredUsers: User[] = [];
  searchTerm = '';
  loading = false;
  errorMessage = '';

  // Modal
  showModal = false;
  modalMode: 'create' | 'edit' | 'password' = 'create';
  selectedUser: Partial<User> = {};
  userForm = {
    email: '',
    password: '',
    role: 'member'
  };
  newPassword = '';
  showPassword = false;
  showNewPassword = false;

  roleOptions = [
    { value: 'member', label: 'Membro' },
    { value: 'admin', label: 'Administrador' }
  ];

  constructor(
    private usersService: UsersService,
    private router: Router
  ) {}

  ngOnInit() {
    this.loadUsers();
  }

  loadUsers() {
    this.loading = true;
    this.errorMessage = '';

    this.usersService.getAllUsers().subscribe({
      next: (users) => {
        this.users = users;
        this.filteredUsers = users;
        this.loading = false;
      },
      error: (error) => {
        console.error('Erro ao carregar usuários:', error);
        this.errorMessage = 'Erro ao carregar usuários. Verifique se você tem permissão de administrador.';
        this.loading = false;
      }
    });
  }

  searchUsers() {
    if (!this.searchTerm.trim()) {
      this.filteredUsers = this.users;
      return;
    }

    const term = this.searchTerm.toLowerCase();
    this.filteredUsers = this.users.filter(user =>
      user.email.toLowerCase().includes(term) ||
      user.member?.name?.toLowerCase().includes(term) ||
      user.role.toLowerCase().includes(term)
    );
  }

  openCreateModal() {
    this.modalMode = 'create';
    this.userForm = {
      email: '',
      password: '',
      role: 'member'
    };
    this.errorMessage = '';
    this.showModal = true;
  }

  openEditModal(user: User) {
    this.modalMode = 'edit';
    this.selectedUser = user;
    this.userForm = {
      email: user.email,
      password: '',
      role: user.role
    };
    this.errorMessage = '';
    this.showModal = true;
  }

  openPasswordModal(user: User) {
    this.modalMode = 'password';
    this.selectedUser = user;
    this.newPassword = '';
    this.errorMessage = '';
    this.showModal = true;
  }

  closeModal() {
    this.showModal = false;
    this.selectedUser = {};
    this.userForm = {
      email: '',
      password: '',
      role: 'member'
    };
    this.newPassword = '';
    this.errorMessage = '';
    this.showPassword = false;
    this.showNewPassword = false;
  }

  togglePasswordVisibility() {
    this.showPassword = !this.showPassword;
  }

  toggleNewPasswordVisibility() {
    this.showNewPassword = !this.showNewPassword;
  }

  saveUser() {
    this.errorMessage = '';

    if (this.modalMode === 'create') {
      if (!this.userForm.email || !this.userForm.password) {
        this.errorMessage = 'Email e senha são obrigatórios';
        return;
      }

      if (this.userForm.password.length < 6) {
        this.errorMessage = 'A senha deve ter no mínimo 6 caracteres';
        return;
      }

      this.loading = true;
      const createData: CreateUserRequest = {
        email: this.userForm.email,
        password: this.userForm.password,
        role: this.userForm.role
      };

      this.usersService.createUser(createData).subscribe({
        next: () => {
          this.loadUsers();
          this.closeModal();
        },
        error: (error) => {
          console.error('Erro ao criar usuário:', error);
          this.errorMessage = error.error?.message || 'Erro ao criar usuário. Email pode já estar em uso.';
          this.loading = false;
        }
      });
    } else if (this.modalMode === 'edit') {
      if (!this.userForm.email) {
        this.errorMessage = 'Email é obrigatório';
        return;
      }

      this.loading = true;
      const updateData: UpdateUserRequest = {
        email: this.userForm.email,
        role: this.userForm.role
      };

      this.usersService.updateUser(this.selectedUser.id!, updateData).subscribe({
        next: () => {
          this.loadUsers();
          this.closeModal();
        },
        error: (error) => {
          console.error('Erro ao atualizar usuário:', error);
          this.errorMessage = error.error?.message || 'Erro ao atualizar usuário';
          this.loading = false;
        }
      });
    }
  }

  changePassword() {
    if (!this.newPassword) {
      this.errorMessage = 'A nova senha é obrigatória';
      return;
    }

    if (this.newPassword.length < 6) {
      this.errorMessage = 'A senha deve ter no mínimo 6 caracteres';
      return;
    }

    this.loading = true;
    this.usersService.changePassword(this.selectedUser.id!, { password: this.newPassword }).subscribe({
      next: () => {
        alert('Senha alterada com sucesso!');
        this.closeModal();
        this.loading = false;
      },
      error: (error) => {
        console.error('Erro ao alterar senha:', error);
        this.errorMessage = 'Erro ao alterar senha';
        this.loading = false;
      }
    });
  }

  deleteUser(user: User) {
    if (!confirm(`Tem certeza que deseja deletar o usuário ${user.email}?`)) {
      return;
    }

    this.loading = true;
    this.usersService.deleteUser(user.id).subscribe({
      next: () => {
        this.loadUsers();
      },
      error: (error) => {
        console.error('Erro ao deletar usuário:', error);
        alert('Erro ao deletar usuário');
        this.loading = false;
      }
    });
  }

  getRoleName(role: string): string {
    return role === 'admin' ? 'Administrador' : 'Membro';
  }

  getRoleBadgeClass(role: string): string {
    return role === 'admin' ? 'role-admin' : 'role-member';
  }
}

<div class="users-page">
  <div class="container">
    <div class="page-header">
      <h1 class="page-title">Gestão de Usuários</h1>
      <button class="btn-primary border-round-lg" (click)="openCreateModal()">
        <i class="pi pi-plus"></i>
        Novo Usuário
      </button>
    </div>

    <!-- Search Bar -->
    <div class="search-container mb-4">
      <div class="search-input-wrapper">
        <i class="pi pi-search"></i>
        <input
          type="text"
          [(ngModel)]="searchTerm"
          (input)="searchUsers()"
          placeholder="Buscar por email, nome ou perfil..."
          class="search-input border-round-lg"
        >
      </div>
    </div>

    <!-- Error Message -->
    <div *ngIf="errorMessage && !showModal" class="error-banner border-round-lg mb-4">
      {{ errorMessage }}
    </div>

    <!-- Loading -->
    <div *ngIf="loading && users.length === 0" class="loading-container">
      <div class="loading-spinner"></div>
      <p>Carregando usuários...</p>
    </div>

    <!-- Users Table -->
    <div *ngIf="!loading || users.length > 0" class="users-table-container">
      <table class="users-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Email</th>
            <th>Perfil</th>
            <th>Membro Vinculado</th>
            <th>Data de Criação</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let user of filteredUsers">
            <td>{{ user.id }}</td>
            <td>{{ user.email }}</td>
            <td>
              <span class="role-badge" [ngClass]="getRoleBadgeClass(user.role)">
                {{ getRoleName(user.role) }}
              </span>
            </td>
            <td>
              <div *ngIf="user.member" class="member-info">
                <div class="member-avatar">
                  <img *ngIf="user.member.photoUrl" [src]="user.member.photoUrl" [alt]="user.member.name">
                  <div *ngIf="!user.member.photoUrl" class="avatar-placeholder">
                    <i class="pi pi-user"></i>
                  </div>
                </div>
                <span>{{ user.member.name }}</span>
              </div>
              <span *ngIf="!user.member" class="text-muted">-</span>
            </td>
            <td>{{ user.createdAt | date: 'dd/MM/yyyy HH:mm' }}</td>
            <td>
              <div class="action-buttons">
                <button class="btn-icon btn-edit" (click)="openEditModal(user)" title="Editar">
                  <i class="pi pi-pencil"></i>
                </button>
                <button class="btn-icon btn-password" (click)="openPasswordModal(user)" title="Trocar Senha">
                  <i class="pi pi-key"></i>
                </button>
                <button class="btn-icon btn-delete" (click)="deleteUser(user)" title="Deletar">
                  <i class="pi pi-trash"></i>
                </button>
              </div>
            </td>
          </tr>
          <tr *ngIf="filteredUsers.length === 0">
            <td colspan="6" class="no-results">
              Nenhum usuário encontrado
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- User Modal -->
<div *ngIf="showModal" class="modal-overlay" (click)="closeModal()">
  <div class="modal-content border-round-lg" (click)="$event.stopPropagation()">
    <div class="modal-header">
      <h2 class="modal-title">
        <span *ngIf="modalMode === 'create'">Novo Usuário</span>
        <span *ngIf="modalMode === 'edit'">Editar Usuário</span>
        <span *ngIf="modalMode === 'password'">Trocar Senha</span>
      </h2>
      <button class="btn-close" (click)="closeModal()">
        <i class="pi pi-times"></i>
      </button>
    </div>

    <div class="modal-body">
      <div *ngIf="errorMessage" class="error-message mb-4">
        <i class="pi pi-exclamation-triangle"></i>
        {{ errorMessage }}
      </div>

      <!-- Create/Edit Form -->
      <form *ngIf="modalMode !== 'password'" (ngSubmit)="saveUser()">
        <div class="form-group">
          <label for="email" class="form-label">Email *</label>
          <input
            type="email"
            id="email"
            [(ngModel)]="userForm.email"
            name="email"
            class="form-input border-round-md w-full"
            required
            placeholder="usuario@exemplo.com"
          >
        </div>

        <div class="form-group" *ngIf="modalMode === 'create'">
          <label for="password" class="form-label">Senha *</label>
          <div class="password-input-wrapper">
            <input
              [type]="showPassword ? 'text' : 'password'"
              id="password"
              [(ngModel)]="userForm.password"
              name="password"
              class="form-input border-round-md w-full"
              required
              placeholder="Mínimo 6 caracteres"
              minlength="6"
            >
            <button
              type="button"
              class="password-toggle-btn"
              (click)="togglePasswordVisibility()"
            >
              <i class="pi" [ngClass]="showPassword ? 'pi-eye-slash' : 'pi-eye'"></i>
            </button>
          </div>
          <small class="form-hint">A senha deve ter no mínimo 6 caracteres</small>
        </div>

        <div class="form-group">
          <label for="role" class="form-label">Perfil *</label>
          <select
            id="role"
            [(ngModel)]="userForm.role"
            name="role"
            class="form-input border-round-md w-full"
            required
          >
            <option *ngFor="let option of roleOptions" [value]="option.value">
              {{ option.label }}
            </option>
          </select>
          <small class="form-hint">Administradores têm acesso total ao sistema</small>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn-secondary border-round-lg" (click)="closeModal()">
            Cancelar
          </button>
          <button type="submit" class="btn-primary border-round-lg" [disabled]="loading">
            <i class="pi" [class.pi-spin]="loading" [class.pi-spinner]="loading" [class.pi-check]="!loading"></i>
            {{ loading ? 'Salvando...' : 'Salvar' }}
          </button>
        </div>
      </form>

      <!-- Change Password Form -->
      <form *ngIf="modalMode === 'password'" (ngSubmit)="changePassword()">
        <div class="user-info-box mb-4">
          <strong>Usuário:</strong> {{ selectedUser.email }}
        </div>

        <div class="form-group">
          <label for="newPassword" class="form-label">Nova Senha *</label>
          <div class="password-input-wrapper">
            <input
              [type]="showNewPassword ? 'text' : 'password'"
              id="newPassword"
              [(ngModel)]="newPassword"
              name="newPassword"
              class="form-input border-round-md w-full"
              required
              placeholder="Mínimo 6 caracteres"
              minlength="6"
            >
            <button
              type="button"
              class="password-toggle-btn"
              (click)="toggleNewPasswordVisibility()"
            >
              <i class="pi" [ngClass]="showNewPassword ? 'pi-eye-slash' : 'pi-eye'"></i>
            </button>
          </div>
          <small class="form-hint">A senha deve ter no mínimo 6 caracteres</small>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn-secondary border-round-lg" (click)="closeModal()">
            Cancelar
          </button>
          <button type="submit" class="btn-primary border-round-lg" [disabled]="loading">
            <i class="pi" [class.pi-spin]="loading" [class.pi-spinner]="loading" [class.pi-key]="!loading"></i>
            {{ loading ? 'Alterando...' : 'Alterar Senha' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
