// src/app/pages/member-form/member-form.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { MembersService, Member } from '../../services/members.service';

@Component({
  selector: 'app-member-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './member-form.component.html',
  styleUrl: './member-form.component.scss'
})
export class MemberFormComponent implements OnInit {
  member: Member = {
    name: '',
    email: '',
    birthDate: '',
    gender: '',
    occupation: '',
    maritalStatus: '',
    primaryPhone: '',
    secondaryPhone: '',
    emergencyContact: '',
    zipCode: '',
    street: '',
    number: '',
    complement: '',
    neighborhood: '',
    city: '',
    state: '',
    churchRole: 'Membro',
    membershipStatus: '',
    baptismDate: '',
    joinDate: '',
    imageConsentGiven: false,
    emailConsentGiven: false,
    whatsappConsentGiven: false,
    notes: ''
  };

  isEditMode = false;
  isLoading = false;
  errorMessage = '';
  memberId: number | null = null;

  // Photo upload
  selectedFile: File | null = null;
  photoPreview: string | null = null;
  isUploadingPhoto = false;

  churchRoleOptions = [
    'Membro',
    'Ministro de Louvor',
    'Lider',
    'Diácono',
    'Presbitero',
    'Pastor/a'
  ];

  maritalStatusOptions = [
    'Solteiro(a)',
    'Casado(a)',
    'Divorciado(a)',
    'Viúvo(a)',
    'Outro'
  ];

  genderOptions = ['Masculino', 'Feminino'];

  membershipStatusOptions = ['Ativo', 'Inativo', 'Visitante', 'Congregado'];

  constructor(
    private membersService: MembersService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit() {
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.memberId = +params['id'];
        this.isEditMode = true;
        this.loadMember();
      }
    });
  }

  loadMember() {
    if (!this.memberId) return;

    this.isLoading = true;
    this.membersService.getMemberById(this.memberId).subscribe({
      next: (member) => {
        this.member = {
          ...member,
          birthDate: member.birthDate ? this.formatDateForInput(member.birthDate) : '',
          baptismDate: member.baptismDate ? this.formatDateForInput(member.baptismDate) : '',
          joinDate: member.joinDate ? this.formatDateForInput(member.joinDate) : '',
          primaryPhone: member.primaryPhone ? this.applyPhoneMask(member.primaryPhone) : '',
          secondaryPhone: member.secondaryPhone ? this.applyPhoneMask(member.secondaryPhone) : '',
          emergencyContact: member.emergencyContact ? this.applyPhoneMask(member.emergencyContact) : '',
          zipCode: member.zipCode ? this.applyZipCodeMask(member.zipCode) : ''
        };

        // Carregar preview da foto se existir
        if (member.photoUrl) {
          this.photoPreview = member.photoUrl;
        }

        this.isLoading = false;
      },
      error: (error) => {
        console.error('Error loading member:', error);
        this.errorMessage = 'Erro ao carregar membro. Tente novamente.';
        this.isLoading = false;
      }
    });
  }

  applyPhoneMask(phone: string): string {
    const value = phone.replace(/\D/g, '');
    let formatted = '';

    if (value.length > 0) {
      formatted = '(' + value.substring(0, 2);

      if (value.length >= 3) {
        formatted += ') ';

        if (value.length <= 10) {
          formatted += value.substring(2, 6);
          if (value.length >= 7) {
            formatted += '-' + value.substring(6, 10);
          }
        } else {
          formatted += value.substring(2, 7);
          if (value.length >= 8) {
            formatted += '-' + value.substring(7, 11);
          }
        }
      }
    }

    return formatted;
  }

  applyZipCodeMask(zipCode: string): string {
    const value = zipCode.replace(/\D/g, '');
    if (value.length > 5) {
      return value.substring(0, 5) + '-' + value.substring(5, 8);
    }
    return value;
  }

  formatDateForInput(dateString: string): string {
    const date = new Date(dateString);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  formatPhoneNumber(event: any, field: 'primaryPhone' | 'secondaryPhone' | 'emergencyContact') {
    let value = event.target.value.replace(/\D/g, '');

    if (value.length > 11) {
      value = value.substring(0, 11);
    }

    let formatted = '';

    if (value.length > 0) {
      formatted = '(' + value.substring(0, 2);

      if (value.length >= 3) {
        formatted += ') ';

        if (value.length <= 10) {
          // Telefone fixo: (34) 3278-2875
          formatted += value.substring(2, 6);
          if (value.length >= 7) {
            formatted += '-' + value.substring(6, 10);
          }
        } else {
          // Celular: (34) 99278-2875
          formatted += value.substring(2, 7);
          if (value.length >= 8) {
            formatted += '-' + value.substring(7, 11);
          }
        }
      }
    }

    this.member[field] = formatted;
  }

  getPhoneNumbersOnly(phone: string): string {
    return phone.replace(/\D/g, '');
  }

  formatZipCode(event: any) {
    let value = event.target.value.replace(/\D/g, '');

    if (value.length > 8) {
      value = value.substring(0, 8);
    }

    if (value.length > 5) {
      value = value.substring(0, 5) + '-' + value.substring(5);
    }

    this.member.zipCode = value;
  }

  saveMember() {
    // Validações de campos obrigatórios
    if (!this.member.name || !this.member.name.trim()) {
      this.errorMessage = 'O nome completo é obrigatório.';
      return;
    }

    if (!this.member.birthDate) {
      this.errorMessage = 'A data de nascimento é obrigatória.';
      return;
    }

    if (!this.member.maritalStatus) {
      this.errorMessage = 'O estado civil é obrigatório.';
      return;
    }

    // Validar se pelo menos um campo de endereço foi preenchido
    const hasAddress = this.member.street || this.member.city || this.member.zipCode;
    if (!hasAddress) {
      this.errorMessage = 'Preencha pelo menos um campo de endereço (CEP, Rua ou Cidade).';
      return;
    }

    // Validar se telefone secundário é diferente do principal
    if (this.member.primaryPhone && this.member.secondaryPhone) {
      const primaryClean = this.getPhoneNumbersOnly(this.member.primaryPhone);
      const secondaryClean = this.getPhoneNumbersOnly(this.member.secondaryPhone);

      if (primaryClean === secondaryClean) {
        this.errorMessage = 'O telefone secundário não pode ser igual ao telefone principal.';
        return;
      }
    }

    this.isLoading = true;
    this.errorMessage = '';

    // Preparar dados para envio (remover máscaras)
    const memberData = {
      ...this.member,
      primaryPhone: this.member.primaryPhone ? this.getPhoneNumbersOnly(this.member.primaryPhone) : '',
      secondaryPhone: this.member.secondaryPhone ? this.getPhoneNumbersOnly(this.member.secondaryPhone) : '',
      emergencyContact: this.member.emergencyContact ? this.getPhoneNumbersOnly(this.member.emergencyContact) : '',
      zipCode: this.member.zipCode ? this.member.zipCode.replace(/\D/g, '') : ''
    };

    if (this.isEditMode && this.memberId) {
      this.membersService.updateMember(this.memberId, memberData).subscribe({
        next: () => {
          // Fazer upload da foto se houver
          this.uploadPhotoIfNeeded(this.memberId!);
        },
        error: (error) => {
          console.error('Error updating member:', error);
          this.errorMessage = 'Erro ao atualizar membro. Tente novamente.';
          this.isLoading = false;
        }
      });
    } else {
      this.membersService.createMember(memberData).subscribe({
        next: (createdMember) => {
          // Fazer upload da foto se houver
          if (createdMember.id) {
            this.uploadPhotoIfNeeded(createdMember.id);
          } else {
            this.isLoading = false;
            this.router.navigate(['/members']);
          }
        },
        error: (error) => {
          console.error('Error creating member:', error);
          this.errorMessage = 'Erro ao criar membro. Tente novamente.';
          this.isLoading = false;
        }
      });
    }
  }

  onFileSelected(event: any) {
    const file = event.target.files[0];
    if (!file) return;

    // Validar tipo de arquivo
    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
    if (!allowedTypes.includes(file.type)) {
      this.errorMessage = 'Tipo de arquivo inválido. Apenas JPEG, PNG e WebP são permitidos.';
      return;
    }

    // Validar tamanho (5MB)
    const maxSize = 5 * 1024 * 1024;
    if (file.size > maxSize) {
      this.errorMessage = 'A imagem deve ter no máximo 5MB.';
      return;
    }

    this.selectedFile = file;
    this.errorMessage = '';

    // Criar preview
    const reader = new FileReader();
    reader.onload = (e: any) => {
      this.photoPreview = e.target.result;
    };
    reader.readAsDataURL(file);
  }

  removePhoto() {
    this.selectedFile = null;
    this.photoPreview = null;

    // Se estiver editando e tinha uma foto, deletar do servidor
    if (this.isEditMode && this.memberId && this.member.photoUrl) {
      if (confirm('Deseja remover a foto deste membro?')) {
        this.isUploadingPhoto = true;
        this.membersService.deletePhoto(this.memberId).subscribe({
          next: () => {
            this.member.photoUrl = undefined;
            this.isUploadingPhoto = false;
          },
          error: (error) => {
            console.error('Error deleting photo:', error);
            this.errorMessage = 'Erro ao deletar foto. Tente novamente.';
            this.isUploadingPhoto = false;
          }
        });
      }
    }
  }

  uploadPhotoIfNeeded(memberId: number) {
    if (!this.selectedFile) {
      this.isLoading = false;
      this.router.navigate(['/members']);
      return;
    }

    this.isUploadingPhoto = true;
    this.membersService.uploadPhoto(memberId, this.selectedFile).subscribe({
      next: (response) => {
        this.isUploadingPhoto = false;
        this.isLoading = false;
        this.router.navigate(['/members']);
      },
      error: (error) => {
        console.error('Error uploading photo:', error);
        this.errorMessage = 'Membro salvo, mas houve erro ao enviar a foto. Tente novamente.';
        this.isUploadingPhoto = false;
        this.isLoading = false;
      }
    });
  }

  cancel() {
    this.router.navigate(['/members']);
  }
}

<div class="member-form-page">
  <div class="container py-6">
    <div class="form-header mb-5">
      <button class="btn-back" (click)="cancel()">
        <i class="pi pi-arrow-left"></i>
        Voltar
      </button>
      <h1 class="form-title">
        {{ isEditMode ? 'Editar Membro' : 'Novo Membro' }}
      </h1>
    </div>

    <div class="form-card border-round-lg">
      <div *ngIf="errorMessage" class="error-message mb-4">
        <i class="pi pi-exclamation-triangle"></i>
        {{ errorMessage }}
      </div>

      <form (ngSubmit)="saveMember()">
        <!-- Photo Upload Section -->
        <div class="form-section">
          <h2 class="section-title">
            <i class="pi pi-image"></i>
            Foto do Membro
          </h2>
          <div class="section-content">
            <div class="photo-upload-container">
              <div class="photo-preview-wrapper">
                <div class="photo-preview" [class.has-photo]="photoPreview">
                  <img *ngIf="photoPreview" [src]="photoPreview" alt="Preview da foto">
                  <div *ngIf="!photoPreview" class="photo-placeholder">
                    <i class="pi pi-user"></i>
                    <p>Nenhuma foto selecionada</p>
                  </div>
                </div>
              </div>

              <div class="photo-actions">
                <label class="btn-upload border-round-lg">
                  <i class="pi pi-upload"></i>
                  {{ photoPreview ? 'Alterar Foto' : 'Selecionar Foto' }}
                  <input
                    type="file"
                    accept="image/jpeg,image/jpg,image/png,image/webp"
                    (change)="onFileSelected($event)"
                    style="display: none;"
                  />
                </label>

                <button
                  *ngIf="photoPreview"
                  type="button"
                  class="btn-remove-photo border-round-lg"
                  (click)="removePhoto()"
                  [disabled]="isUploadingPhoto"
                >
                  <i class="pi pi-trash"></i>
                  Remover Foto
                </button>

                <p class="photo-hint">
                  Formatos aceitos: JPEG, PNG, WebP. Tamanho máximo: 5MB.
                </p>
              </div>
            </div>
          </div>
        </div>

        <!-- Basic Information Section -->
        <div class="form-section">
          <h2 class="section-title">
            <i class="pi pi-user"></i>
            Informações Básicas
          </h2>
          <div class="section-content">
            <div class="grid">
              <div class="col-12 md:col-6">
                <label class="form-label">Nome Completo *</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [(ngModel)]="member.name"
                  name="name"
                  required
                  placeholder="Digite o nome completo"
                />
              </div>

              <div class="col-12 md:col-6">
                <label class="form-label">Email</label>
                <input
                  type="email"
                  class="form-input w-full"
                  [(ngModel)]="member.email"
                  name="email"
                  placeholder="email@exemplo.com"
                />
              </div>

              <div class="col-12 md:col-4">
                <label class="form-label">Data de Nascimento *</label>
                <input
                  type="date"
                  class="form-input w-full"
                  [(ngModel)]="member.birthDate"
                  name="birthDate"
                  required
                />
              </div>

              <div class="col-12 md:col-4">
                <label class="form-label">Gênero</label>
                <select class="form-input w-full" [(ngModel)]="member.gender" name="gender">
                  <option value="">Selecione...</option>
                  <option *ngFor="let option of genderOptions" [value]="option">
                    {{ option }}
                  </option>
                </select>
              </div>

              <div class="col-12 md:col-4">
                <label class="form-label">Estado Civil *</label>
                <select class="form-input w-full" [(ngModel)]="member.maritalStatus" name="maritalStatus" required>
                  <option value="">Selecione...</option>
                  <option *ngFor="let option of maritalStatusOptions" [value]="option">
                    {{ option }}
                  </option>
                </select>
              </div>

              <div class="col-12">
                <label class="form-label">Profissão</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [(ngModel)]="member.occupation"
                  name="occupation"
                  placeholder="Profissão"
                />
              </div>
            </div>
          </div>
        </div>

        <!-- Contact Information Section -->
        <div class="form-section">
          <h2 class="section-title">
            <i class="pi pi-phone"></i>
            Informações de Contato
          </h2>
          <div class="section-content">
            <div class="grid">
              <div class="col-12 md:col-4">
                <label class="form-label">Telefone Principal</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [value]="member.primaryPhone"
                  (input)="formatPhoneNumber($event, 'primaryPhone')"
                  name="primaryPhone"
                  placeholder="(34) 99278-2875"
                  maxlength="15"
                />
              </div>

              <div class="col-12 md:col-4">
                <label class="form-label">Telefone Secundário</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [value]="member.secondaryPhone"
                  (input)="formatPhoneNumber($event, 'secondaryPhone')"
                  name="secondaryPhone"
                  placeholder="(34) 99278-2875"
                  maxlength="15"
                />
              </div>

              <div class="col-12 md:col-4">
                <label class="form-label">Contato de Emergência</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [value]="member.emergencyContact"
                  (input)="formatPhoneNumber($event, 'emergencyContact')"
                  name="emergencyContact"
                  placeholder="(34) 99278-2875"
                  maxlength="15"
                />
              </div>
            </div>
          </div>
        </div>

        <!-- Address Section -->
        <div class="form-section">
          <h2 class="section-title">
            <i class="pi pi-map-marker"></i>
            Endereço *
          </h2>
          <div class="section-content">
            <p class="field-hint mb-3">* Preencha pelo menos um campo de endereço</p>
            <div class="grid">
              <div class="col-12 md:col-3">
                <label class="form-label">CEP</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [value]="member.zipCode"
                  (input)="formatZipCode($event)"
                  name="zipCode"
                  placeholder="00000-000"
                  maxlength="9"
                />
              </div>

              <div class="col-12 md:col-7">
                <label class="form-label">Rua/Avenida</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [(ngModel)]="member.street"
                  name="street"
                  placeholder="Nome da rua"
                />
              </div>

              <div class="col-12 md:col-2">
                <label class="form-label">Número</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [(ngModel)]="member.number"
                  name="number"
                  placeholder="123"
                />
              </div>

              <div class="col-12 md:col-4">
                <label class="form-label">Complemento</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [(ngModel)]="member.complement"
                  name="complement"
                  placeholder="Apto, bloco, etc."
                />
              </div>

              <div class="col-12 md:col-4">
                <label class="form-label">Bairro</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [(ngModel)]="member.neighborhood"
                  name="neighborhood"
                  placeholder="Bairro"
                />
              </div>

              <div class="col-12 md:col-3">
                <label class="form-label">Cidade</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [(ngModel)]="member.city"
                  name="city"
                  placeholder="Cidade"
                />
              </div>

              <div class="col-12 md:col-1">
                <label class="form-label">Estado</label>
                <input
                  type="text"
                  class="form-input w-full"
                  [(ngModel)]="member.state"
                  name="state"
                  placeholder="UF"
                  maxlength="2"
                />
              </div>
            </div>
          </div>
        </div>

        <!-- Church Information Section -->
        <div class="form-section">
          <h2 class="section-title">
            <i class="pi pi-home"></i>
            Informações Eclesiásticas
          </h2>
          <div class="section-content">
            <div class="grid">
              <div class="col-12 md:col-6">
                <label class="form-label">Função na Igreja</label>
                <select class="form-input w-full" [(ngModel)]="member.churchRole" name="churchRole">
                  <option *ngFor="let role of churchRoleOptions" [value]="role">
                    {{ role }}
                  </option>
                </select>
              </div>

              <div class="col-12 md:col-6">
                <label class="form-label">Status de Membro</label>
                <select class="form-input w-full" [(ngModel)]="member.membershipStatus" name="membershipStatus">
                  <option value="">Selecione...</option>
                  <option *ngFor="let status of membershipStatusOptions" [value]="status">
                    {{ status }}
                  </option>
                </select>
              </div>

              <div class="col-12 md:col-6">
                <label class="form-label">Data de Batismo</label>
                <input
                  type="date"
                  class="form-input w-full"
                  [(ngModel)]="member.baptismDate"
                  name="baptismDate"
                />
              </div>

              <div class="col-12 md:col-6">
                <label class="form-label">Data de Ingresso</label>
                <input
                  type="date"
                  class="form-input w-full"
                  [(ngModel)]="member.joinDate"
                  name="joinDate"
                />
              </div>
            </div>
          </div>
        </div>

        <!-- Consent Section -->
        <div class="form-section">
          <h2 class="section-title">
            <i class="pi pi-shield"></i>
            Consentimentos
          </h2>
          <div class="section-content">
            <div class="consent-group">
              <label class="consent-label">
                <input
                  type="checkbox"
                  [(ngModel)]="member.imageConsentGiven"
                  name="imageConsentGiven"
                  class="consent-checkbox"
                />
                <span class="consent-text">
                  <strong>Uso de Imagem:</strong> Autorizo o uso da minha imagem em fotos e vídeos para divulgação das atividades da igreja.
                </span>
              </label>
            </div>

            <div class="consent-group">
              <label class="consent-label">
                <input
                  type="checkbox"
                  [(ngModel)]="member.emailConsentGiven"
                  name="emailConsentGiven"
                  class="consent-checkbox"
                />
                <span class="consent-text">
                  <strong>Comunicação por E-mail:</strong> Autorizo o recebimento de informações e mensagens por e-mail.
                </span>
              </label>
            </div>

            <div class="consent-group">
              <label class="consent-label">
                <input
                  type="checkbox"
                  [(ngModel)]="member.whatsappConsentGiven"
                  name="whatsappConsentGiven"
                  class="consent-checkbox"
                />
                <span class="consent-text">
                  <strong>Comunicação por WhatsApp:</strong> Autorizo o recebimento de informações e mensagens por WhatsApp.
                </span>
              </label>
            </div>
          </div>
        </div>

        <!-- Notes Section -->
        <div class="form-section">
          <h2 class="section-title">
            <i class="pi pi-file-edit"></i>
            Observações
          </h2>
          <div class="section-content">
            <textarea
              class="form-textarea w-full"
              [(ngModel)]="member.notes"
              name="notes"
              rows="4"
              placeholder="Observações adicionais..."
            ></textarea>
          </div>
        </div>

        <!-- Form Actions -->
        <div class="form-actions">
          <button
            type="button"
            class="btn btn-cancel border-round-lg"
            (click)="cancel()"
            [disabled]="isLoading"
          >
            Cancelar
          </button>
          <button
            type="submit"
            class="btn btn-save border-round-lg"
            [disabled]="isLoading || isUploadingPhoto || !member.name"
          >
            <i class="pi" [class.pi-spin]="isLoading || isUploadingPhoto" [class.pi-spinner]="isLoading || isUploadingPhoto" [class.pi-check]="!isLoading && !isUploadingPhoto"></i>
            {{ (isLoading || isUploadingPhoto) ? (isUploadingPhoto ? 'Enviando foto...' : 'Salvando...') : 'Salvar Membro' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// src/pages/MemberForm.tsx
import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowLeft, Upload, X, Save, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { useToast } from '@/hooks/use-toast';
import { mockMembers } from '@/data/mockMembers';
import {
  genderLabels,
  maritalStatusLabels,
  churchRoleLabels,
  membershipStatusLabels,
  Gender,
  MaritalStatus,
  ChurchRole,
  MembershipStatus,
} from '@/types/member';

const formSchema = z.object({
  photo: z.string().optional(),
  name: z.string().min(1, 'Nome é obrigatório').max(100, 'Nome deve ter no máximo 100 caracteres'),
  email: z.string().min(1, 'Email é obrigatório').email('Email inválido'),
  birthDate: z.string().min(1, 'Data de nascimento é obrigatória'),
  gender: z.enum(['male', 'female'], { required_error: 'Gênero é obrigatório' }),
  maritalStatus: z.enum(['single', 'married', 'divorced', 'widowed', 'other'], {
    required_error: 'Estado civil é obrigatório',
  }),
  occupation: z.string().min(1, 'Profissão é obrigatória').max(100, 'Profissão deve ter no máximo 100 caracteres'),
  primaryPhone: z.string().min(1, 'Telefone principal é obrigatório'),
  secondaryPhone: z.string().optional(),
  emergencyContact: z.string().optional(),
  zipCode: z.string().optional(),
  street: z.string().optional(),
  number: z.string().optional(),
  complement: z.string().optional(),
  neighborhood: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  churchRole: z.enum(['member', 'worship_minister', 'leader', 'deacon', 'elder', 'pastor']).optional(),
  membershipStatus: z.enum(['active', 'inactive', 'visitor', 'congregant']).optional(),
  baptismDate: z.string().optional(),
  joinDate: z.string().optional(),
  imageConsentGiven: z.boolean().optional(),
  emailConsentGiven: z.boolean().optional(),
  whatsappConsentGiven: z.boolean().optional(),
  notes: z.string().optional(),
});

type FormData = z.infer<typeof formSchema>;

const brazilianStates = [
  'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA',
  'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN',
  'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO',
];

const MemberForm = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const { toast } = useToast();
  const isEditing = !!id;
  
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [isLoadingCep, setIsLoadingCep] = useState(false);

  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      photo: '',
      name: '',
      email: '',
      birthDate: '',
      gender: undefined,
      maritalStatus: undefined,
      occupation: '',
      primaryPhone: '',
      secondaryPhone: '',
      emergencyContact: '',
      zipCode: '',
      street: '',
      number: '',
      complement: '',
      neighborhood: '',
      city: '',
      state: '',
      churchRole: undefined,
      membershipStatus: undefined,
      baptismDate: '',
      joinDate: '',
      imageConsentGiven: false,
      emailConsentGiven: false,
      whatsappConsentGiven: false,
      notes: '',
    },
  });

  // Load member data when editing
  useEffect(() => {
    if (isEditing && id) {
      const member = mockMembers.find((m) => m.id === id);
      if (member) {
        form.reset({
          photo: member.photo || '',
          name: member.name,
          email: member.email,
          birthDate: member.birthDate,
          gender: member.gender,
          maritalStatus: member.maritalStatus,
          occupation: member.occupation,
          primaryPhone: member.primaryPhone,
          secondaryPhone: member.secondaryPhone || '',
          emergencyContact: member.emergencyContact || '',
          zipCode: member.zipCode || '',
          street: member.street || '',
          number: member.number || '',
          complement: member.complement || '',
          neighborhood: member.neighborhood || '',
          city: member.city || '',
          state: member.state || '',
          churchRole: member.churchRole,
          membershipStatus: member.membershipStatus,
          baptismDate: member.baptismDate || '',
          joinDate: member.joinDate || '',
          imageConsentGiven: member.imageConsentGiven || false,
          emailConsentGiven: member.emailConsentGiven || false,
          whatsappConsentGiven: member.whatsappConsentGiven || false,
          notes: member.notes || '',
        });
        if (member.photo) {
          setPhotoPreview(member.photo);
        }
      }
    }
  }, [isEditing, id, form]);

  const handlePhotoChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        toast({
          title: 'Erro',
          description: 'A foto deve ter no máximo 5MB',
          variant: 'destructive',
        });
        return;
      }
      const reader = new FileReader();
      reader.onloadend = () => {
        const result = reader.result as string;
        setPhotoPreview(result);
        form.setValue('photo', result);
      };
      reader.readAsDataURL(file);
    }
  };

  const removePhoto = () => {
    setPhotoPreview(null);
    form.setValue('photo', '');
  };

  const fetchAddressByCep = async (cep: string) => {
    const cleanCep = cep.replace(/\D/g, '');
    if (cleanCep.length !== 8) return;

    setIsLoadingCep(true);
    try {
      const response = await fetch(`https://viacep.com.br/ws/${cleanCep}/json/`);
      const data = await response.json();
      
      if (!data.erro) {
        form.setValue('street', data.logradouro || '');
        form.setValue('neighborhood', data.bairro || '');
        form.setValue('city', data.localidade || '');
        form.setValue('state', data.uf || '');
      }
    } catch (error) {
      console.error('Erro ao buscar CEP:', error);
    } finally {
      setIsLoadingCep(false);
    }
  };

  const onSubmit = (data: FormData) => {
    console.log('Form data:', data);
    toast({
      title: isEditing ? 'Membro atualizado!' : 'Membro cadastrado!',
      description: `${data.name} foi ${isEditing ? 'atualizado' : 'cadastrado'} com sucesso.`,
    });
    navigate('/members');
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Header */}
        <div className="mb-8">
          <Button
            variant="ghost"
            onClick={() => navigate('/members')}
            className="mb-4"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Voltar para lista
          </Button>
          <h1 className="text-3xl font-bold text-foreground">
            {isEditing ? 'Editar Membro' : 'Novo Membro'}
          </h1>
          <p className="text-muted-foreground mt-1">
            {isEditing
              ? 'Atualize as informações do membro'
              : 'Preencha as informações para cadastrar um novo membro'}
          </p>
        </div>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
            {/* Foto */}
            <Card>
              <CardHeader>
                <CardTitle>Foto</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-6">
                  <div className="relative">
                    {photoPreview ? (
                      <div className="relative">
                        <img
                          src={photoPreview}
                          alt="Preview"
                          className="w-32 h-32 rounded-full object-cover border-4 border-border"
                        />
                        <button
                          type="button"
                          onClick={removePhoto}
                          className="absolute -top-2 -right-2 p-1 bg-destructive text-destructive-foreground rounded-full"
                        >
                          <X className="h-4 w-4" />
                        </button>
                      </div>
                    ) : (
                      <div className="w-32 h-32 rounded-full bg-muted flex items-center justify-center border-4 border-dashed border-border">
                        <Upload className="h-8 w-8 text-muted-foreground" />
                      </div>
                    )}
                  </div>
                  <div>
                    <Input
                      type="file"
                      accept="image/jpeg,image/png,image/webp"
                      onChange={handlePhotoChange}
                      className="max-w-xs"
                    />
                    <p className="text-sm text-muted-foreground mt-2">
                      JPEG, PNG ou WebP. Máximo 5MB.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Informações Pessoais */}
            <Card>
              <CardHeader>
                <CardTitle>Informações Pessoais</CardTitle>
              </CardHeader>
              <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField
                  control={form.control}
                  name="name"
                  render={({ field }) => (
                    <FormItem className="md:col-span-2">
                      <FormLabel>Nome Completo *</FormLabel>
                      <FormControl>
                        <Input placeholder="Digite o nome completo" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="email"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Email *</FormLabel>
                      <FormControl>
                        <Input type="email" placeholder="email@exemplo.com" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="birthDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Data de Nascimento *</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="gender"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Gênero *</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Selecione o gênero" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {Object.entries(genderLabels).map(([value, label]) => (
                            <SelectItem key={value} value={value}>
                              {label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="maritalStatus"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Estado Civil *</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Selecione o estado civil" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {Object.entries(maritalStatusLabels).map(([value, label]) => (
                            <SelectItem key={value} value={value}>
                              {label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="occupation"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Profissão *</FormLabel>
                      <FormControl>
                        <Input placeholder="Digite a profissão" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            {/* Contato */}
            <Card>
              <CardHeader>
                <CardTitle>Contato</CardTitle>
              </CardHeader>
              <CardContent className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <FormField
                  control={form.control}
                  name="primaryPhone"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Telefone Principal *</FormLabel>
                      <FormControl>
                        <Input placeholder="(11) 99999-9999" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="secondaryPhone"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Telefone Secundário</FormLabel>
                      <FormControl>
                        <Input placeholder="(11) 99999-9999" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="emergencyContact"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Contato de Emergência</FormLabel>
                      <FormControl>
                        <Input placeholder="(11) 99999-9999" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            {/* Endereço */}
            <Card>
              <CardHeader>
                <CardTitle>Endereço</CardTitle>
              </CardHeader>
              <CardContent className="grid grid-cols-1 md:grid-cols-6 gap-6">
                <FormField
                  control={form.control}
                  name="zipCode"
                  render={({ field }) => (
                    <FormItem className="md:col-span-2">
                      <FormLabel>CEP</FormLabel>
                      <FormControl>
                        <div className="relative">
                          <Input
                            placeholder="00000-000"
                            {...field}
                            onBlur={(e) => {
                              field.onBlur();
                              fetchAddressByCep(e.target.value);
                            }}
                          />
                          {isLoadingCep && (
                            <Loader2 className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 animate-spin" />
                          )}
                        </div>
                      </FormControl>
                      <FormDescription>Digite o CEP para buscar o endereço</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="street"
                  render={({ field }) => (
                    <FormItem className="md:col-span-4">
                      <FormLabel>Rua/Avenida</FormLabel>
                      <FormControl>
                        <Input placeholder="Nome da rua" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="number"
                  render={({ field }) => (
                    <FormItem className="md:col-span-1">
                      <FormLabel>Número</FormLabel>
                      <FormControl>
                        <Input placeholder="Nº" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="complement"
                  render={({ field }) => (
                    <FormItem className="md:col-span-2">
                      <FormLabel>Complemento</FormLabel>
                      <FormControl>
                        <Input placeholder="Apto, Bloco, etc." {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="neighborhood"
                  render={({ field }) => (
                    <FormItem className="md:col-span-3">
                      <FormLabel>Bairro</FormLabel>
                      <FormControl>
                        <Input placeholder="Nome do bairro" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="city"
                  render={({ field }) => (
                    <FormItem className="md:col-span-4">
                      <FormLabel>Cidade</FormLabel>
                      <FormControl>
                        <Input placeholder="Nome da cidade" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="state"
                  render={({ field }) => (
                    <FormItem className="md:col-span-2">
                      <FormLabel>UF</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="UF" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {brazilianStates.map((state) => (
                            <SelectItem key={state} value={state}>
                              {state}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            {/* Informações Eclesiásticas */}
            <Card>
              <CardHeader>
                <CardTitle>Informações Eclesiásticas</CardTitle>
              </CardHeader>
              <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField
                  control={form.control}
                  name="churchRole"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Função na Igreja</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Selecione a função" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {Object.entries(churchRoleLabels).map(([value, label]) => (
                            <SelectItem key={value} value={value}>
                              {label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="membershipStatus"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Status de Membro</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Selecione o status" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {Object.entries(membershipStatusLabels).map(([value, label]) => (
                            <SelectItem key={value} value={value}>
                              {label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="baptismDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Data de Batismo</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="joinDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Data de Adesão</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            {/* Consentimentos */}
            <Card>
              <CardHeader>
                <CardTitle>Consentimentos</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <FormField
                  control={form.control}
                  name="imageConsentGiven"
                  render={({ field }) => (
                    <FormItem className="flex flex-row items-start space-x-3 space-y-0">
                      <FormControl>
                        <Checkbox
                          checked={field.value}
                          onCheckedChange={field.onChange}
                        />
                      </FormControl>
                      <div className="space-y-1 leading-none">
                        <FormLabel>Autorizo o uso da minha imagem</FormLabel>
                        <FormDescription>
                          Permite o uso de fotos e vídeos em materiais da igreja
                        </FormDescription>
                      </div>
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="emailConsentGiven"
                  render={({ field }) => (
                    <FormItem className="flex flex-row items-start space-x-3 space-y-0">
                      <FormControl>
                        <Checkbox
                          checked={field.value}
                          onCheckedChange={field.onChange}
                        />
                      </FormControl>
                      <div className="space-y-1 leading-none">
                        <FormLabel>Autorizo comunicação por e-mail</FormLabel>
                        <FormDescription>
                          Receba avisos e novidades por e-mail
                        </FormDescription>
                      </div>
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="whatsappConsentGiven"
                  render={({ field }) => (
                    <FormItem className="flex flex-row items-start space-x-3 space-y-0">
                      <FormControl>
                        <Checkbox
                          checked={field.value}
                          onCheckedChange={field.onChange}
                        />
                      </FormControl>
                      <div className="space-y-1 leading-none">
                        <FormLabel>Autorizo comunicação por WhatsApp</FormLabel>
                        <FormDescription>
                          Receba avisos e novidades por WhatsApp
                        </FormDescription>
                      </div>
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            {/* Observações */}
            <Card>
              <CardHeader>
                <CardTitle>Observações</CardTitle>
              </CardHeader>
              <CardContent>
                <FormField
                  control={form.control}
                  name="notes"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Notas/Observações</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="Informações adicionais sobre o membro..."
                          className="min-h-[120px]"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            {/* Actions */}
            <div className="flex justify-end gap-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => navigate('/members')}
              >
                Cancelar
              </Button>
              <Button type="submit">
                <Save className="mr-2 h-4 w-4" />
                {isEditing ? 'Salvar Alterações' : 'Cadastrar Membro'}
              </Button>
            </div>
          </form>
        </Form>
      </div>
    </div>
  );
};

export default MemberForm;
