// src/app/components/verses-section/verses-section.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-verses-section',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './verses-section.component.html',
  styleUrl: './verses-section.component.scss'
})
export class VersesSectionComponent {

}

<section class="verses-section">
  <div class="verses-background">
    <div class="verses-overlay"></div>
    <div class="floating-element element-1"></div>
    <div class="floating-element element-2"></div>
    <div class="floating-element element-3"></div>
  </div>

  <div class="container">
    <div class="verses-header">
      <div class="header-icon">
        <i class="pi pi-book"></i>
      </div>
      <h2 class="verses-title">Versículos que nos Guiam</h2>
      <p class="verses-subtitle">Fundamentos bíblicos do nosso ministério</p>
    </div>

    <div class="verses-grid">
      <!-- Versículo 1: Apocalipse 3:11 -->
      <div class="verse-card" data-verse="1">
        <div class="card-icon-wrapper">
          <div class="icon-circle">
            <i class="pi pi-crown"></i>
          </div>
          <div class="icon-glow"></div>
        </div>

        <div class="card-content">
          <div class="verse-reference">
            <i class="pi pi-bookmark"></i>
            <span>Apocalipse 3:11</span>
          </div>

          <blockquote class="verse-text">
            "Eis que venho sem demora; guarda o que tens, para que ninguém tome a tua coroa."
          </blockquote>

          <div class="verse-theme">
            <i class="pi pi-star"></i>
            <span>Perseverança e Vitória</span>
          </div>
        </div>

        <div class="card-decoration"></div>
      </div>

      <!-- Versículo 2: Hebreus 10:38-39 -->
      <div class="verse-card" data-verse="2">
        <div class="card-icon-wrapper">
          <div class="icon-circle">
            <i class="pi pi-shield"></i>
          </div>
          <div class="icon-glow"></div>
        </div>

        <div class="card-content">
          <div class="verse-reference">
            <i class="pi pi-bookmark"></i>
            <span>Hebreus 10:38-39</span>
          </div>

          <blockquote class="verse-text">
            "Mas o justo viverá pela fé; E, se ele recuar, a minha alma não tem prazer nele. Nós, porém, não somos daqueles que se retiram para a perdição, mas daqueles que creem para a conservação da alma."
          </blockquote>

          <div class="verse-theme">
            <i class="pi pi-star"></i>
            <span>Fé e Firmeza</span>
          </div>
        </div>

        <div class="card-decoration"></div>
      </div>

      <!-- Versículo 3: Romanos 1:16 -->
      <div class="verse-card" data-verse="3">
        <div class="card-icon-wrapper">
          <div class="icon-circle">
            <i class="pi pi-bolt"></i>
          </div>
          <div class="icon-glow"></div>
        </div>

        <div class="card-content">
          <div class="verse-reference">
            <i class="pi pi-bookmark"></i>
            <span>Romanos 1:16</span>
          </div>

          <blockquote class="verse-text">
            "Eu não me envergonho do evangelho, pois ele é o poder de Deus para salvar todos os que creem, primeiro os judeus e também os não judeus."
          </blockquote>

          <div class="verse-theme">
            <i class="pi pi-star"></i>
            <span>Poder do Evangelho</span>
          </div>
        </div>

        <div class="card-decoration"></div>
      </div>
    </div>

    <!-- Call to Action -->
    <div class="verses-cta">
      <div class="cta-content">
        <i class="pi pi-heart-fill"></i>
        <p>Estes versículos são a base da nossa missão e nos inspiram diariamente</p>
      </div>
    </div>
  </div>
</section>

// src/components/VersesSection.tsx
import { Crown, Flame, Zap } from "lucide-react";

const verses = [
  {
    icon: Crown,
    reference: "Apocalipse 3:11",
    text: "Eis que venho sem demora; guarda o que tens, para que ninguém tome a tua coroa.",
  },
  {
    icon: Flame,
    reference: "Hebreus 10:38-39",
    text: "Mas o meu justo viverá da fé; e, se retroceder, nele não se compraz a minha alma. Nós, porém, não somos dos que retrocedem para a perdição; somos, entretanto, da fé, para a conservação da alma.",
  },
  {
    icon: Zap,
    reference: "Romanos 1:16",
    text: "Pois não me envergonho do evangelho, porque é o poder de Deus para a salvação de todo aquele que crê.",
  },
];

const VersesSection = () => {
  return (
    <section className="py-20 bg-background">
      <div className="container mx-auto px-4">
        {/* Section Header */}
        <div className="text-center mb-14">
          <span className="text-golden font-semibold text-sm uppercase tracking-widest">
            Versículos que nos Guiam
          </span>
          <h2 className="mt-3 text-3xl md:text-4xl font-bold text-secondary">
            Versículos
          </h2>
        </div>

        {/* Verses Grid */}
        <div className="grid md:grid-cols-3 gap-6 max-w-6xl mx-auto">
          {verses.map((verse) => (
            <div
              key={verse.reference}
              className="group p-6 bg-muted/50 rounded-xl border border-border hover:border-golden/30 transition-all duration-300 hover:shadow-lg"
            >
              {/* Icon */}
              <div className="w-12 h-12 rounded-lg bg-golden/10 flex items-center justify-center mb-5 group-hover:bg-golden/20 transition-colors">
                <verse.icon className="w-6 h-6 text-golden" />
              </div>

              {/* Reference */}
              <h3 className="text-golden font-bold text-lg mb-3">
                {verse.reference}
              </h3>

              {/* Text */}
              <p className="text-muted-foreground leading-relaxed text-sm">
                {verse.text}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default VersesSection;
